const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./routes/schedeA.js','./routes/schedeOA.js','./routes/schedeRA.js','./routes/schedeGpm.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "VASARI API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Schede A",
            "description": "Routes"
        },
        {
            "name": "Schede OA",
            "description": "Routes"
        },
        {
           "name": "Schede RA",
            "description": "Routes"
        },
        {
            "name": "Schede Gpm",
            "description": "Routes"
        }
    ],
    definitions: {
        Scheda_A: {
            
                rs: {
                    rst: [
                        {
                            rsti: 1920,
                            rstr: "Facciata",
                            rstf: 1923,
                            rstt: [
                                "Demolizione apposizioni moderne e ricreazione della facciata romanica"
                            ]
                        }
                    ]
                },
                cm: {
                    fur: [
                        "P.M."
                    ],
                    cmp: {
                        cmpd: 2021,
                        cmpdn: [
                            "P.M."
                        ]
                    }
                },
                au: {
                    aut: [
                        {
                            autn: "Abate Elia",
                            autm: [
                                "bibliografia"
                            ],
                            autr: "Commissionante",
                            autb: "Chiesa Cattolica",
                            auth: "Ab.El.",
                            auta: "1120/1186"
                        }
                    ]
                },
                rv: {
                    rse: [
                        {
                            rser: "luogo di collocazione/localizzazione",
                            rsec: "15594",
                            rset: "A"
                        }
                    ]
                },
                lc: {
                    pvc: {
                        pvcr: "Puglia",
                        pvcs: "Italia",
                        pvcc: "Bari",
                        pvcp: "BA"
                    }
                },
                og: {
                    ogt: {
                        ogtd: [
                            {
                                value: "Museo",
                                language: "it",
                                profile: "guest"
                            },
                            {
                                value: "Museum",
                                language: "en",
                                profile: "guest"
                            }
                        ],
                        ogtn: [
                            {
                                value: "Museo Nicolaiano",
                                language: "it",
                                profile: "guest"
                            },
                            {
                                value: "St. Nicholas' Museum",
                                language: "en",
                                profile: "guest"
                            }
                        ]
                    }
                },
                cd: {
                    ntc: {
                        ntcs: "ST",
                        ntcr: "16",
                        ntcn: "123456"
                    },
                    lir: "I",
                    esc: "PoliBa",
                    tsk: "A"
                },
                li: {
                    lsi: [
                        {
                            lsiu: "Timpano",
                            lsim: [
                                "Pietra calcarea"
                            ],
                            lsit: "Stemma ovale dei domenicani",
                            lsic: "Incisione",
                            lsii: "In hoc signo vinces",
                            lsig: "Stemma"
                        }
                    ]
                }
        },

        Scheda_OA:{
            mt: {
                mtc: [
                    "tela di lino/tempera"
                ],
                mis: [
                    {
                        miss: 8,
                        misl: 172,
                        misu: "cm",
                        misn: 278
                    }
                ]
            },
            rs: {
                rst: [
                    {
                        rste: "Stato",
                        rstd: "1975"
                    }
                ]
            },
            co: {
                stc: {
                    stcc: "buono"
                }
            },
            dt: [
                {
                    dts: {
                        dtsi: "1485",
                        dtsf: "1485"
                    }
                }
            ],
            cm: {
                cmp: {
                    cmpd: 2021,
                    cmpn: [
                        "Cuscito, Francesco"
                    ]
                }
            },
            au: {
                aut: [
                    {
                        autn: "Botticelli",
                        autm: [
                            "firma"
                        ],
                        auta: "1444 ca./1510"
                    }
                ],
                atb: [
                    {
                        atbd: "Ambito fiorentino"
                    }
                ]
            },
            rv: {
                rse: [
                    {
                        rser: "luogo di collocazione/Localizzazione",
                        rsec: "15401",
                        rset: "OA"
                    }
                ]
            },
            lc: {
                pvc: {
                    pvcr: "Toscana",
                    pvcs: "Italia",
                    pvcc: "Firenze",
                    pvcp: "FI"
                },
                ldc: {
                    ldcn: "Galleria degli Uffizi",
                    ldcu: "Piazzale degli Uffizi, 6, 50122 Firenze FI"
                }
            },
            og: {
                sgt: {
                    sgtt: [
                        {
                            value: "Venere che esce dalle acque",
                            language: "it",
                            profile: "guest"
                        },
                        {
                            value: "Venus exiting from waters",
                            language: "en",
                            profile: "guest"
                        }
                    ],
                    sgti: [
                        {
                            value: "Allegoria della nascita di Venere",
                            language: "it",
                            profile: "guest"
                        },
                        {
                            value: "Allegory of the birth of Venus",
                            language: "en",
                            profile: "guest"
                        }
                    ]
                },
                ogt: {
                    ogtd: [
                        {
                            value: "Dipinto",
                            language: "it",
                            profile: "guest"
                        },
                        {
                            value: "Painting",
                            language: "en",
                            profile: "guest"
                        }
                    ],
                    ogtn: [
                        {
                            value: "Nascita di Venere",
                            language: "it",
                            profile: "guest"
                        },
                        {
                            value: "Birth of Venus",
                            language: "en",
                            profile: "guest"
                        }
                    ]
                }
            },
            cd: {
                tsk: "OA"
            },
            ub: {
                inv: [
                    {
                        invc: "CSP-IVB",
                        invd: "2020",
                        invn: "12243554"
                    }
                ]
            }
        },
        
        Scheda_RA:{
            
            mt: {
                mtc: [
                    "Ceramica/dipinto"
                ],
                mis: [
                    {
                        misl: 35,
                        misn: 35,
                        misg: 569.45,
                        miss: 4,
                        misd: 35,
                        misu: "cm",
                        misp: 4,
                        misa: 35
                    }
                ]
            },
            co: {
                stc: {
                    stcc: "discreto"
                }
            },
            cm: {
                fur: [
                    "Concept Reply"
                ],
                cmp: {
                    cmpd: 2021,
                    cmpn: [
                        "Concept Reply"
                    ]
                }
            },
            au: {
                aut: [
                    {
                        autn: "Bruno della Spina",
                        ncun: "173393AU",
                        autm: [
                            "firma"
                        ],
                        autr: "Pittore",
                        auta: "1520/1578"
                    }
                ],
                atb: [
                    {
                        atbd: "bottega fiorentina"
                    }
                ]
            },
            rv: {
                rse: [
                    {
                        rser: "luogo di collocazione/Localizzazione",
                        rsec: "15421",
                        rset: "A"
                    }
                ]
            },
            lc: {
                pvc: {
                    pvcr: "Toscana",
                    pvcs: "Italia",
                    pvcc: "Firenze",
                    pvcp: "FI"
                },
                ldc: {
                    ldcn: "Museo del Bargello",
                    ldcu: "Via del Proconsolo 4, Fi, Firenze"
                }
            },
            og: {
                sgt: {
                    sgtt: [
                        {
                            value: "Capra brucante",
                            language: "it",
                            profile: "guest"
                        }
                    ],
                    sgti: [
                        {
                            value: "Allegoria della vita che è un piatto fugace da mordere all'occorrenza",
                            language: "it",
                            profile: "guest"
                        }
                    ]
                },
                ogt: {
                    ogtd: [
                        {
                            value: "Piatto in ceramica",
                            language: "it",
                            profile: "guest"
                        }
                    ],
                    ogtt: "Piatto",
                    ogtn: [
                        {
                            value: "Piatto della capra brucante",
                            language: "it",
                            profile: "guest"
                        }
                    ]
                }
            },
            cd: {
                ecp: "A662",
                ntc: {
                    ntcs: "RA",
                    ntcr: "13",
                    ntcn: "13443556"
                },
                lir: "I",
                esc: "A662",
                tsk: "RA"
            },
            ub: {
                inv: [
                    {
                        invc: "INVC-1",
                        invd: "1998",
                        invn: "INVN-34532"
                    }
                ]
            },
            da: {
                isr: [
                    {
                        isri: "Bruno della Spina",
                        isrl: "Italiano",
                        isrm: "cm 9",
                        isrc: "Iscrizione",
                        isrs: "pittura",
                        isrp: "orlo",
                        isra: "Brun de la Spina",
                        isrt: "latini"
                    }
                ]
            }
        },

        Scheda_Gpm:{
            pi: {
                    pig: {
                    pigc: 0,
                    pigd: []
                    },
                    pis: {
                    pist: 0,
                    pism: 100,
                    pisx: 140,
                    pisl: [
                        "it",
                        "en"
                    ],
                    pisa: 7
                    },
                    pio: {
                    pion: [
                        "Musei Vaticani"
                    ],
                    pioa: "Percorso base per visitare le opere fondamentali del Rinascimento."
                    },
                    pic: {
                    pici: "[15414;15411;15402]",
                    picn: "[;;;]",
                    picm: "[15433A,15415I,15434V;15412I;15425A,15403I,15416I,15426V]",
                    picr: "[152893;152894;152895;152897]",
                    pice: "[152896I;152898I;152899A,152900I;152901I]",
                    pico: true,
                    picv: 0
                    }
            },
            cb: {
                    cbt: {
                    cbtw: [
                        {
                        cbtw_1: "Occidentali",
                        cbtw_2: "Italiana"
                        },
                        {
                        cbtw_1: "Moderna",
                        cbtw_2: "Rinascimento"
                        }
                    ],
                    cbtc: [
                        {
                        cbtc_1: "Arte",
                        cbtc_2: "Arti visive",
                        cbtc_3: "Pittura"
                        },
                        {
                        cbtc_1: "Opere d'arte visiva",
                        cbtc_2: "Opere d'arte figurativa",
                        cbtc_3: "Dipinti"
                        }
                    ],
                    cbtq: [
                        {
                        cbtq_1: "Secondo millennio",
                        cbtq_2: "sec. XVI"
                        },
                        {
                        cbtq_1: "Secondo millennio",
                        cbtq_2: "sec. XV"
                        }
                    ],
                    cbta: [
                        {
                        cbta_1: "Posti riservati a disabili"
                        },
                        {
                        cbta_1: "Servizi per disabili in carrozzella",
                        cbta_2: "Ascensori/montascale per disabili"
                        }
                    ]
                    }
            },
            geolocation: {
                geometry: {
                    coordinates: [
                        11.255924999713898,
                        43.76852162810477
                    ],
                    type: "point"
                    },
                    system: "WGS84"
                },
            abstract: [
                {
                    value: "Attraverso questo percorso potrete scoprire l'evoluzione del Rinascimento nella Città del Vaticano, partendo dalle sue origini, fino al suo declino, grazie all'introduzione di alcune delle opere più rappresentative di questo periodo.",
                    language: "it",
                    profile: "guest"
                },
                {
                    value: "Through this path you can discover the evolution of the Renaissance in Vatican City, starting from its origins, up to its decline, thanks to the introduction of some of the most representative works of this period.",
                    language: "en",
                    profile: "guest"
                }
            ]  
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app.js')
})